export const siteConfig = {
  name: 'Pratik Neupane',
  title: 'Pratik Neupane | Senior Backend & Systems Engineer',
  description:
    'Senior Backend & Systems Engineer with 5+ years of production experience architecting distributed platforms, Agentic AI pipelines, deterministic state machines, and high-concurrency cloud systems.',
  url: 'https://pratikneupane.dev',
  ogImage: '/og-image.png',
  author: 'Pratik Neupane',
  links: {
    github: 'https://github.com/l3-h6',
    linkedin: 'https://linkedin.com/in/pratikneupane',
    email: 'pratikneupane@proton.me',
  },
  keywords: [
    'Pratik Neupane',
    'Pratik',
    'l3-h6',
    'pratikneupane',
    'Software Engineer in Nepal',
    'Developer in Nepal',
    'Backend Developer Nepal',
    'Senior Backend Engineer Nepal',
    'Systems Engineer Nepal',
    'Nepal Software Engineer',
    'Kathmandu Developer',
    'Senior Software Engineer',
    'Backend Engineer',
    'Systems Engineering',
    'Agentic AI',
    'AI Engineer Nepal',
    'RAG',
    'Vector DB',
    'Pinecone',
    'Kubernetes',
    'Linux Internals',
    'Cloud Architecture',
    'Distributed Systems',
    'Node.js',
    'TypeScript',
    'Go',
    'Golang',
    'PostgreSQL',
    'Redis',
  ],
} as const;
